name: Rebase Container Branch

on:
  workflow_run:
    workflows: ["Sync Fork"]
    types:
      - completed
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: container
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clean workspace
        run: |
          git reset --hard
          git clean -fdx

      - name: Git Quick Rebase
        run: |
          git fetch origin main
          git rebase origin/main
      - name: Post-Failure Debugging
        if: failure()
        run: |
          git status
          git diff

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PR_AGENT_GITHUB_TOKEN }}
        run: git push --force
